server.port=8080;
# DataSource Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_user
spring.datasource.username=root
spring.datasource.password=12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

## Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

##Eureka server
eureka.client.service-url.default-zone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

jwt.secret=RzpYXtS1I1hAOYBgyYXRC0p5VNoO2TA7yod5Wf9vWb4M6S+gXIfXH0B94NqI6eGmH5ujNeZoOXcm3hGo+Pb58A==
